services:
  fichador:
    build: .
    container_name: fichador-holded
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/fichador.db
      - TZ=Europe/Madrid
      - HEADLESS=false
      - DISPLAY=:99
    env_file:
      - .env
    shm_size: '2gb'
